version: '3.8'

services:
  fdownloader:
    build: .
    image: fdownloader
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    # We will change the command/entrypoint to run the web server
    command: python app.py

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http fdownloader:5000
    environment:
      NGROK_AUTHTOKEN: 2iEfF4Og18LspOL2t5msunr248T_2UcwHzR7RMFiWMzKTWcr4
    ports:
      - 4040:4040
    depends_on:
      - fdownloader
